### ISSUE TITLE
Spam users thanks to logintoboggan

### ISSUE THREAD

**Issue by CarlQLange** [datagovuk/dgu_d7#480]
Hey there,

I don't believe you guys have this issue, but I thought I'd document it for future reference anyway.
We were seeing a large number of spam users created, despite the face that we had "only allow admins to create user" enabled (which should disable the signup form). This is because we were using the unified login/signup form for logintoboggan, which only hides the signup form with a `display:none;`, which is not good enough to stop bots from trying to sign up. The solution was to not use the unified form.

Just in case anyone else has this issue :) This could be closed immediately, it's only for documentation.

Cheers,
Carl

**Comment by ratajczak** [comment]
Thanks for flagging this up @CarlQLange
